GPUS: '0,1'
DATA_DIR: ''
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 500
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  DATASET: mpii
  ROOT: '/media/sf_N_DRIVE/randd/MachineLearning/TeamMembers/Anuar/data/optical/teeth_and_wear/hydraulic/try8'
  TEST_SET: valid
  TRAIN_SET: train
  FLIP: false
  ROT_FACTOR: 7
  SCALE_FACTOR: 0.125
  TRANSL_STD: 16
MODEL:
  NAME: pose_resnet
  PRETRAINED: '/home/cheng/Desktop/repos/bucket-tracking/keypoints/models/pytorch/imagenet/resnet50-19c8e357.pth'
  IMAGE_SIZE:
  - 96
  - 192
  NUM_JOINTS: 5
  EXTRA:
    TARGET_TYPE: gaussian
    SIGMA: 2
    HEATMAP_SIZE:
    - 24
    - 48
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 18
LOSS:
  USE_TARGET_WEIGHT: false
TRAIN:
  BATCH_SIZE: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 13
  RESUME: false
  OPTIMIZER: adam
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 10
  - 12
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 8
  FLIP_TEST: false
  MODEL_FILE: ''
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
